name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'

categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📖 Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

template: |
  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'enhancement'
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: 'bug'
    branch:
      - '/^fix[/-].+/'
      - '/^hotfix[/-].+/'
  - label: 'documentation'
    branch:
      - '/^doc(s)?[/-].+/'
  # 以下のラベルは自動付与されても、上記 categories に含まれなければリリースノートには載らない
  - label: 'test'
    branch:
      - '/^test[/-].+/'
  - label: 'refactor'
    branch:
      - '/^refactor[/-].+/'