name: CI

on:
  workflow_dispatch:
  push:
    branches: 
      - 'feature-*'
      - 'feature/*'
    paths: ['**/*.ts', '**/*.tsx', '**/*.js', '.github/**', '**/*.json']

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actions-security:
    uses: Suntory-Y-Water/my-github-actions-ci/.github/workflows/reusable-actions-security.yml@main

  typescript-ci:
    uses: Suntory-Y-Water/my-github-actions-ci/.github/workflows/reusable-typescript-ci.yml@main
    with:
      node-version: '20'
      pnpm-version: '9'
      timeout-minutes: 15
      version-check: true