name: CI

on:
  # feature-またはfeature/で始まるPRでのみ実行する
  push:
    branches: 
      - 'feature-*'
      - 'feature/*'

jobs:
  build_lint_test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # pnpmの依存関係キャッシュを有効化

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm run build

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm test
