name: Create Release on Main Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions: {}

jobs:
  release:
    # PRがマージされ、かつマージ元のブランチが 'feature' で始まる場合のみ実行
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          # release-drafter が全てのコミット履歴を解析できるようにするため
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"

      - name: Get version from package.json
        id: package_version
        run: |
          # package.json からバージョンを読み取り、出力変数に設定
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - name: Create Release Tag and Note
        uses: release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97 # v6.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # package.jsonから取得した純粋なバージョン番号を渡す
          version: ${{ steps.package_version.outputs.version }}
          publish: true # リリースを自動公開
          config-name: release-drafter.yml
